name: smart_home_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  dropdown_button2: ^1.9.2
  equatable: ^2.0.5
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_database: ^10.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^3.0.0
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.1.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  hidden_drawer_menu: ^3.0.1
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^2.2.0
  mockito: ^5.4.0
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  slide_to_act: ^2.0.1
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
